fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
        exclude: .vscode
      - id: end-of-file-fixer
        exclude: ".*\\.mk?d"
      - id: trailing-whitespace
        exclude: ".*\\.mk?d"

-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v16.0.3'
    hooks:
      - id: clang-format
        exclude_types: [javascript, json]
