name: macOS CI Test

on:
  push:
    branches: [ "main", "master", "dev", "devel" ]
  pull_request:
    branches: [ "main", "master", "dev", "devel" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: prepare
      run: |
        make prepare
    - name: configure
      run: |
        cmake -H. -Bbuild -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Debug"
    - name: building
      run: |
        # cmake --build build --config Debug --target unit_tests -j4
        cmake --build build

    - name: testing
      run: |
        # cd build
        # cd tests
        # ./unit_tests
        cmake -E chdir build ctest
